name: Zillow Analysis and Website Update

on:
  workflow_run:
    workflows: ["Scrape Zillow Listings"]
    types: [completed]
  push:
    paths:
      - "zillow_properties.csv"  # Trigger if the CSV is updated

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install pandas openai

      - name: Run Property Analysis Script
        run: python .github/scripts/generate_property_analysis.py

      - name: Commit and Push Analysis
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add _includes/analysis.md
          git commit -m "Update property analysis"
          git push
