name: Zillow Analysis and Website Update

on:
  workflow_run:
    workflows: ["Scrape Zillow Listings"]
    types: [completed]
  push:
    paths:
      - "zillow_properties.csv"

jobs:
  analysis:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Download the artifact using the GitHub CLI with authentication via GH_TOKEN.
      - name: Download CSV Artifact using GitHub CLI
        if: ${{ github.event_name == 'workflow_run' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Downloading artifact from upstream run id: ${{ github.event.workflow_run.id }}"
          gh run download ${{ github.event.workflow_run.id }} -n zillow_properties_csv --dir .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install pandas openai

      - name: Run Property Analysis Script
        run: python .github/scripts/generate_property_analysis.py

      - name: Commit and Push Analysis
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add _includes/analysis.md
          git commit -m "Update property analysis"
          git push
